[package]
name = "vanitygen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concread = "0.2.16"
hex = "0.4.3"
rayon = "1.5.1"
structopt = "0.3.22"
sp-core = "^3.0.0"
